# example netlify.toml

[functions]
  directory = "dist/functions"

[context.production.environment]
  CI = "false"

[build]
  command = "astro build && cp -a dist/netlify/functions/. dist/functions/"
  functions = "netlify/functions"
  publish = "dist"