# example netlify.toml

[functions]
  directory = "lambda"

[context.production.environment]
  CI = "false"

[build]
  #command = "astro build && cp -a netlify/functions/. dist/functions/"
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"